In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
pd.set_option('display.max_columns', 500)

In [3]:
df = pd.read_csv('data/datastep1.csv')

Columns to keep:
- CITY_LOCATION_IDENTIFIER__UP_TO_9_ALPHANUMERIC_CHARACTERS_
- OBSERVATION_TIME_IN_LST__LOCAL_STANDARD_TIME___STRING_AS_YYYYMMDDHHMM_
- SKY_DESCRIPTOR__INTEGER___SEE_LOOKUP_
- PRECIPITATION_DESCRIPTOR__INTEGER___SEE_LOOKUP_
- TEMPERATURE_DESCRIPTOR__INTEGER___SEE_LOOKUP_
- TEMPERATURE__FLOATING_POINT___CELSIUS_
- WIND_SPEED__FLOATING_POINT___KNOTS__
- WIND_DIRECTION__INTEGER___COMPASS_DEGREES__0___359__0____NORTH_	
- WIND_SPEED__FLOATING_POINT___KNOTS__
- HUMIDITY__INTEGER___PERCENT_	
- DEW_POINT__FLOATING_POINT___CELSIUS_
- SEA_LEVEL_PRESSURE__FLOATING_POINT___MILLIBARS_
- BAROMETRIC_TENDENCY__S___STEADY__F___FALLING__R___RISING_
- VISIBILITY__FLOATING_POINT___MILES_
- SKY_CONDITIONS__C_LEAR_F_EW_S_CATTERED_B_ROKEN_O_VERCAST__X_OBSCURED_
- MINIMUM_CLOUD_BASE__FLOATING_POINT___METERS_
- MAXIMUM_CLOUD_BASE__FLOATING_POINT___METERS_

In [52]:
df

,Unnamed: 0,CITY_LOCATION_IDENTIFIER__UP_TO_9_ALPHANUMERIC_CHARACTERS_,OBSERVATION_TIME_IN_UTC__STRING_AS_YYYYMMDDHHMM_,OBSERVATION_TIME_IN_LST__LOCAL_STANDARD_TIME___STRING_AS_YYYYMMDDHHMM_,OBSERVATION_TIME_IN_LOCAL_TIME__STRING_AS_YYYYMMDDHHMM_,DAYLIGHT_STATUS__CHARACTER___D_FOR_DAYTIME_ICONS__N_FOR_NIGHTTIME_ICONS_,SKY_DESCRIPTOR__INTEGER___SEE_LOOKUP_,PRECIPITATION_DESCRIPTOR__INTEGER___SEE_LOOKUP_,TEMPERATURE_DESCRIPTOR__INTEGER___SEE_LOOKUP_,ADDITIONAL_AIR_DESCRIPTOR__OPTIONAL___INTEGER___SEE_LOOKUP_,TEMPERATURE__FLOATING_POINT___CELSIUS_,WIND_SPEED__FLOATING_POINT___KNOTS__,WIND_DIRECTION__INTEGER___COMPASS_DEGREES__0___359__0____NORTH_,WIND_GUSTS__OPTIONAL___FLOATING__POINT___KNOTS__,HUMIDITY__INTEGER___PERCENT_,DEW_POINT__FLOATING_POINT___CELSIUS_,COMFORT_LEVEL__FLOATING_POINT___CELSIUS_,SEA_LEVEL_PRESSURE__FLOATING_POINT___MILLIBARS_,BAROMETRIC_TENDENCY__S___STEADY__F___FALLING__R___RISING_,VISIBILITY__FLOATING_POINT___MILES_,SKY_CONDITIONS__C_LEAR_F_EW_S_CATTERED_B_ROKEN_O_VERCAST__X_OBSCURED_,MINIMUM_CLOUD_BASE__FLOATING_POINT___METERS_,MAXIMUM_CLOUD_BASE__FLOATING_POINT___METERS_,WEATHER_TYPE___FC___TORNADO_WATERSPOUT__FC___FUNNEL_CLOUD__TS___THUNDERSTORM__GR___HAIL__RA___RAIN__DZ___DRIZZLE__SN___SNOW__SG___SNOW_GRAINS__GS___SMALL_HAIL___OR_SNOW_PELLETS__PE___ICE_PELLETS__IC___CRYSTALS__FG____HEAVY_FOG_LESS_THAN_0_25_MILES_VIS__FG,HOURLY_PRECIP____OPTIONAL___FLOATING__POINT___CENTIMETERS_,_3_HOUR_PRECIPITATION__OPTIONAL___FLOATING__POINT___CENTIMETERS_,_6_HOUR_PRECIPITATION__OPTIONAL___FLOATING__POINT___CENTIMETERS_,_12_HOUR_PRECIPITATION__OPTIONAL___FLOATING__POINT___CENTIMETERS_,_24_HOUR_PRECIPITATION__OPTIONAL___FLOATING__POINT___CENTIMETERS_,_24_HR_MAXIMUM_TEMPERATURE__OPTIONAL___FLOATING_POINT___CELSIUS_,_6_HOUR_MAXIMUM_TEMPERATURE__OPTIONAL___FLOATING_POINT___CELSIUS_,_24_HR_MINIMUM_TEMPERATURE__OPTIONAL___FLOATING_POINT___CELSIUS_,_6_HOUR_MINIMUM_TEMPERATURE__OPTIONAL___FLOATING_POINT___CELSIUS_,SNOW_COVER__OPTIONAL___FLOATING__POINT___CENTIMETERS_,SOLAR_RADIATION__OPTIONAL___INTEGER___MINUTES_
0,1409,KRFD,202409010500,202408312300,202409010000,N,2.0,*,8.0,*,17.8,7.56,160.0,*,90.0,16.1,17.80,1015.6,*,16.09,C,22.0,NaN,*,0,*,*,*,*,*,*,*,*,*,*
1,1410,KRFD,202409010600,202409010000,202409010100,N,2.0,*,8.0,*,17.8,7.56,180.0,*,90.0,16.1,17.80,1015.4,R,16.09,C,22.0,NaN,*,0,*,*,*,*,*,24.4,*,17.2,*,*
2,1411,KRFD,202409010700,202409010100,202409010200,N,2.0,*,8.0,*,17.8,7.56,180.0,*,90.0,16.1,17.80,1015.0,*,16.09,C,22.0,NaN,*,0,*,*,*,*,*,*,*,*,*,*
3,1412,KRFD,202409010800,202409010200,202409010300,N,2.0,*,8.0,*,17.8,7.56,160.0,*,90.0,16.1,17.80,1014.3,*,16.09,C,22.0,NaN,*,0,*,*,*,*,*,*,*,*,*,*
4,1413,KRFD,202409010900,202409010300,202409010400,N,2.0,*,8.0,*,18.9,7.56,270.0,*,84.0,16.1,18.90,1014.8,R,16.09,C,22.0,NaN,*,0,*,*,*,*,*,*,*,*,*,*
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1900857,1814604,KJVL,202103010100,202102281900,202102281900,N,7.0,*,4.0,*,2.0,9.36,270.0,*,81.0,-1.0,-0.76,1012.2,*,16.09,S,4572.0,4572.0,*,*,*,*,*,*,*,*,*,*,*,*
1900858,1814605,KJVL,202103010200,202102282000,202102282000,N,7.0,*,4.0,*,2.0,20.52,290.0,*,75.0,-2.0,-2.79,1012.9,F,16.09,S,4572.0,4572.0,*,*,*,*,*,*,*,*,*,*,*,*
1900859,1814606,KJVL,202103010300,202102282100,202102282100,N,2.0,*,4.0,*,1.7,24.12,290.0,*,70.0,-3.3,-3.62,1014.9,F,16.09,C,22.0,732.0,*,0,*,*,*,*,*,*,*,*,*,*
1900860,1814607,KJVL,202103010400,202102282200,202102282200,N,2.0,*,4.0,*,0.0,16.56,290.0,*,87.0,-2.0,-4.70,1014.2,*,16.09,C,22.0,NaN,*,*,*,*,*,*,*,*,*,*,*,*
1900861,1814608,KJVL,202103010500,202102282300,202102282300,N,2.0,*,4.0,*,0.0,16.56,290.0,*,80.0,-3.0,-4.70,1014.9,F,16.09,C,22.0,NaN,*,*,*,*,*,*,*,*,*,*,*,*

In [44]:
columns_to_keep = [
    "CITY_LOCATION_IDENTIFIER__UP_TO_9_ALPHANUMERIC_CHARACTERS_",
    "OBSERVATION_TIME_IN_LST__LOCAL_STANDARD_TIME___STRING_AS_YYYYMMDDHHMM_",
    "SKY_DESCRIPTOR__INTEGER___SEE_LOOKUP_",
    "PRECIPITATION_DESCRIPTOR__INTEGER___SEE_LOOKUP_",
    "TEMPERATURE_DESCRIPTOR__INTEGER___SEE_LOOKUP_",
    "TEMPERATURE__FLOATING_POINT___CELSIUS_",
    "WIND_SPEED__FLOATING_POINT___KNOTS__",
    "WIND_DIRECTION__INTEGER___COMPASS_DEGREES__0___359__0____NORTH_",
    "HUMIDITY__INTEGER___PERCENT_",
    "DEW_POINT__FLOATING_POINT___CELSIUS_",
    "SEA_LEVEL_PRESSURE__FLOATING_POINT___MILLIBARS_",
    "BAROMETRIC_TENDENCY__S___STEADY__F___FALLING__R___RISING_",
    "VISIBILITY__FLOATING_POINT___MILES_",
    "SKY_CONDITIONS__C_LEAR_F_EW_S_CATTERED_B_ROKEN_O_VERCAST__X_OBSCURED_",
    "MINIMUM_CLOUD_BASE__FLOATING_POINT___METERS_",
    "MAXIMUM_CLOUD_BASE__FLOATING_POINT___METERS_",
]

In [45]:
df2 = df[columns_to_keep]

In [43]:
df2

,CITY_LOCATION_IDENTIFIER__UP_TO_9_ALPHANUMERIC_CHARACTERS_,OBSERVATION_TIME_IN_LST__LOCAL_STANDARD_TIME___STRING_AS_YYYYMMDDHHMM_,SKY_DESCRIPTOR__INTEGER___SEE_LOOKUP_,PRECIPITATION_DESCRIPTOR__INTEGER___SEE_LOOKUP_,TEMPERATURE_DESCRIPTOR__INTEGER___SEE_LOOKUP_,TEMPERATURE__FLOATING_POINT___CELSIUS_,WIND_SPEED__FLOATING_POINT___KNOTS__,WIND_DIRECTION__INTEGER___COMPASS_DEGREES__0___359__0____NORTH_,WIND_SPEED__FLOATING_POINT___KNOTS__,HUMIDITY__INTEGER___PERCENT_,DEW_POINT__FLOATING_POINT___CELSIUS_,SEA_LEVEL_PRESSURE__FLOATING_POINT___MILLIBARS_,BAROMETRIC_TENDENCY__S___STEADY__F___FALLING__R___RISING_,VISIBILITY__FLOATING_POINT___MILES_,SKY_CONDITIONS__C_LEAR_F_EW_S_CATTERED_B_ROKEN_O_VERCAST__X_OBSCURED_,MINIMUM_CLOUD_BASE__FLOATING_POINT___METERS_,MAXIMUM_CLOUD_BASE__FLOATING_POINT___METERS_
0,KRFD,202408312300,2.0,*,8.0,17.8,7.56,160.0,7.56,90.0,16.1,1015.6,*,16.09,C,22.0,NaN
1,KRFD,202409010000,2.0,*,8.0,17.8,7.56,180.0,7.56,90.0,16.1,1015.4,R,16.09,C,22.0,NaN
2,KRFD,202409010100,2.0,*,8.0,17.8,7.56,180.0,7.56,90.0,16.1,1015.0,*,16.09,C,22.0,NaN
3,KRFD,202409010200,2.0,*,8.0,17.8,7.56,160.0,7.56,90.0,16.1,1014.3,*,16.09,C,22.0,NaN
4,KRFD,202409010300,2.0,*,8.0,18.9,7.56,270.0,7.56,84.0,16.1,1014.8,R,16.09,C,22.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1900857,KJVL,202102281900,7.0,*,4.0,2.0,9.36,270.0,9.36,81.0,-1.0,1012.2,*,16.09,S,4572.0,4572.0
1900858,KJVL,202102282000,7.0,*,4.0,2.0,20.52,290.0,20.52,75.0,-2.0,1012.9,F,16.09,S,4572.0,4572.0
1900859,KJVL,202102282100,2.0,*,4.0,1.7,24.12,290.0,24.12,70.0,-3.3,1014.9,F,16.09,C,22.0,732.0
1900860,KJVL,202102282200,2.0,*,4.0,0.0,16.56,290.0,16.56,87.0,-2.0,1014.2,*,16.09,C,22.0,NaN
1900861,KJVL,202102282300,2.0,*,4.0,0.0,16.56,290.0,16.56,80.0,-3.0,1014.9,F,16.09,C,22.0,NaN

In [47]:
dict_rename = {
    "CITY_LOCATION_IDENTIFIER__UP_TO_9_ALPHANUMERIC_CHARACTERS_":'id',
    "OBSERVATION_TIME_IN_LST__LOCAL_STANDARD_TIME___STRING_AS_YYYYMMDDHHMM_":'datetime',
    "SKY_DESCRIPTOR__INTEGER___SEE_LOOKUP_":'skydescriptor',
    "PRECIPITATION_DESCRIPTOR__INTEGER___SEE_LOOKUP_":'rain',
    "TEMPERATURE_DESCRIPTOR__INTEGER___SEE_LOOKUP_":'temp_str',
    "TEMPERATURE__FLOATING_POINT___CELSIUS_":'temp',
    "WIND_SPEED__FLOATING_POINT___KNOTS__":'windspeed',
    "WIND_DIRECTION__INTEGER___COMPASS_DEGREES__0___359__0____NORTH_":'winddirection',
    "HUMIDITY__INTEGER___PERCENT_":'humidity',
    "DEW_POINT__FLOATING_POINT___CELSIUS_":'dew',
    "SEA_LEVEL_PRESSURE__FLOATING_POINT___MILLIBARS_":'sealevel',
    "BAROMETRIC_TENDENCY__S___STEADY__F___FALLING__R___RISING_":'barometric',
    "VISIBILITY__FLOATING_POINT___MILES_":'visibility',
    "SKY_CONDITIONS__C_LEAR_F_EW_S_CATTERED_B_ROKEN_O_VERCAST__X_OBSCURED_":'skycondition',
    "MINIMUM_CLOUD_BASE__FLOATING_POINT___METERS_":'mincloud',
    "MAXIMUM_CLOUD_BASE__FLOATING_POINT___METERS_":'maxcloud',
}

In [49]:
df3 = df2.rename(columns=dict_rename)

In [51]:
df3.to_csv('data/datastep2.csv', index=False)

In [50]:
df3

,id,datetime,skydescriptor,rain,temp_str,temp,windspeed,winddirection,humidity,dew,sealevel,barometric,visibility,skycondition,mincloud,maxcloud
0,KRFD,202408312300,2.0,*,8.0,17.8,7.56,160.0,90.0,16.1,1015.6,*,16.09,C,22.0,NaN
1,KRFD,202409010000,2.0,*,8.0,17.8,7.56,180.0,90.0,16.1,1015.4,R,16.09,C,22.0,NaN
2,KRFD,202409010100,2.0,*,8.0,17.8,7.56,180.0,90.0,16.1,1015.0,*,16.09,C,22.0,NaN
3,KRFD,202409010200,2.0,*,8.0,17.8,7.56,160.0,90.0,16.1,1014.3,*,16.09,C,22.0,NaN
4,KRFD,202409010300,2.0,*,8.0,18.9,7.56,270.0,84.0,16.1,1014.8,R,16.09,C,22.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1900857,KJVL,202102281900,7.0,*,4.0,2.0,9.36,270.0,81.0,-1.0,1012.2,*,16.09,S,4572.0,4572.0
1900858,KJVL,202102282000,7.0,*,4.0,2.0,20.52,290.0,75.0,-2.0,1012.9,F,16.09,S,4572.0,4572.0
1900859,KJVL,202102282100,2.0,*,4.0,1.7,24.12,290.0,70.0,-3.3,1014.9,F,16.09,C,22.0,732.0
1900860,KJVL,202102282200,2.0,*,4.0,0.0,16.56,290.0,87.0,-2.0,1014.2,*,16.09,C,22.0,NaN
1900861,KJVL,202102282300,2.0,*,4.0,0.0,16.56,290.0,80.0,-3.0,1014.9,F,16.09,C,22.0,NaN